# SPDX-FileCopyrightText: © 2024 Emanuel Mancio <emanuelmancio@usp.br>
#
# SPDX-License-Identifier: GPL-3.0-only

[project]
name = "MolClusters"
version = "0.4.0"
description = "Tool to analyze cluster formation in molecular dynamics simulations"
authors = [{ name = "Emanuel Mancio", email = "emanuelmancio@usp.br" }]
license = "GPL-3.0-only"
license-files = ["LICENSE", "COPYING", "LICENSES/*.txt"]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "numpy>=2.2.4,<3.0.0",
    "networkx>=3.4.2,<4.0.0",
    "mdanalysis[analysis]>=2.9.0,<3.0.0",
    "pyyaml>=6.0.2,<7.0.0",
    "tqdm>=4.67.1,<5.0.0",
    "pandas>=2.2.3,<3.0.0",
    "pydantic-settings>=2.14.2,<3.0.0",
    "pydantic>=2.12.5,<3.0.0",
    "loguru>=0.7.3,<0.8.0",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics",
    "Private :: Do Not Upload",
]

[project.urls]
repository = "https://github.com/EmanuelMancio/MolClusters"

[project.scripts]
molclusters = "molclusters.main:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3,<10.0.0",
    "ruff>=0.11.4,<0.12.0",
    "pytest-cov>=5.0.0,<6.0.0",
    "pre-commit>=4.2.0,<5.0.0",
    "commitizen>=4.5.1,<5.0.0",
    "reuse>=6.0.0,<7.0.0",
]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib --cov=src --cov-report html"

[tool.commitizen]
name = "cz_conventional_commits"
version_provider = "pep621"
version_scheme = "semver2"
update_changelog_on_bump = true
gpg_sign = true
annotated_tag = true
bump_message = "chore: release $current_version -> $new_version [skip-ci]"
changelog_incremental = true
major_version_zero = true

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
