# SPDX-FileCopyrightText: © 2025 Emanuel Mancio <emanuelmancio@usp.br>
#
# SPDX-License-Identifier: CC0-1.0

[pytest]
addopts = -rA --show-capture=stderr --import-mode=importlib --cov=src --cov-report html
testpaths = tests
