version = 1

[[annotations]]
path = ["src/molclusters/**/*.py","tests/**/*.py"]
SPDX-FileCopyrightText = "© 2026 Emanuel Mancio <emanuelmancio@usp.br>"
SPDX-License-Identifier = "GPL-3.0-only"

[[annotations]]
path = [
    "tests/data/**/*.mdp",
    "tests/data/**/*.gro",
    "tests/data/**/*.top",
    "tests/data/**/*.yml",
    "tests/data/**/*.tpr",
    "tests/data/**/*.pdb",
    "tests/data/**/*.data"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

# Computer-generated file.
[[annotations]]
path = ["uv.lock"]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"